# This file contains metadata for backstage
# Read more about available fields and annotations:
# https://github.com/tradeshift/backstage
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Hej
  description: "Hi med dig"
  annotations:
    github.com/project-slug: Tradeshift/Hej
spec:
  type: other
  lifecycle: experimental
  owner: babelway
